### ISSUE TITLE
Failed to render and update auto layout status

### ISSUE THREAD

**Issue by ddempseyCard** [colinjpratt/swift-ios-toggle-button#1]
Received this layout error:

IB Designables: Failed to render and update auto layout status...

Easy to fix by adding:

    override init(frame: CGRect) {
        super.init(frame: frame)
    }

https://stackoverflow.com/questions/31265906/ibdesignable-crashing-agent

**Comment by colinjpratt** [comment]
Thank you @ddempseyCard Ive added your suggestion to the code.
